name: Build and Push Disk Access Image
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/utility-box-docker
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}    
    - name: Set image version
      run: |
        echo "VERSION=$(echo '${{ github.sha }}' | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV       
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.VERSION }},${{ env.IMAGE_NAME }}:latest
